### ISSUE TITLE
Check group

### ISSUE THREAD

**Issue by jonatannietoa** [tom-smith-okta/okta-api-center#4]
Hello, our **API Gateway** is working with **OKTA**, but we do not know where can we check **OKTA GROUPS**. For example if the user has "group1" they will **authorize**, if not have group **unauthorized**.

**Comment by sedkis** [comment]
@jonatannietoa, you could map those roles to a JWT claim, and then setup Tyk to apply Authorization based off each claim to determine if a claim has access to X set of APIs
