### ISSUE TITLE
Programmatic access?

### ISSUE THREAD

**Issue by pablote** [tom-smith-okta/okta-api-center#9]
I understand this obtains an access token from the OIDC handshake, which is then used as a bearer token to query the API.

If I wanted to query the API directly programmatically, not from web app, but from a batch job for example, how can I obtain an access token in that case?

thanks

**Comment by tom-smith-okta** [comment]
In that case you would use the client credentials flow: https://developer.okta.com/docs/guides/implement-client-creds/use-flow/
